### ISSUE TITLE
Does not work on OSX

### ISSUE THREAD

**Issue by Spareo** [totango/helm-ssm#5]
```
[SSM] Options: upgrade --install --namespace=teller bitgo-express charts/bitgo-express/
[SSM] Value files: environment/crypto-eng-usva-1.yaml
[SSM] Reading environment/crypto-eng-usva-1.yaml
[SSM] Found 1 parameters
[SSM] Parameters: 
{{ssm /clusters/crypto-eng-usva-1/cryptocortex/BitGoRoleArn us-east-1}}
===============================================
sed: 1: "s:{{ssm /clusters/crypt ...": bad flag in substitute command: 'a'
```

I get this error every time I run it and nothing gets templated into my values file. Im running on OSX 10.14.4 and helm version 2.13.1

**Comment by amitlt** [comment]
does the value that is being replace happen to have a colon character in it?

**Comment by Spareo** [comment]
Yes it is an IAM role ARN

**Comment by amitlt** [comment]
I've updated the script to be able to take in special characters (except `|`), so you should now be able to use an arn as a value.

I've tested the change with `arn:aws:iam::671587110562:role/system/some-role & asd ^asd !@#` as a value and it worked fine, so let me know if you encounter any issues
